#!/bin/bash

# A helper script to push content to GitHub
# Cheers! Addy

# Check if there is unfetched online files
echo -e "\e[34mChecking if there is an unfetched file from the repository\e[0m"
git pull

# Add every files in the project folder
git add --all .

# Add commit message
echo -e "\e[33mWrite your commit comment!\e[0m"
read -e COMMENT

# Add some details to commit message
TIME=$(date +"%a %-d %b %g at %H:%M")
git commit -m "Comment : $COMMENT on $TIME"

# Push the local files to github
git push -u origin master
echo -e "\e[35mDone!\e[0m"
