#!/bin/bash

# A helper script to setup Git
# Originally written by Monsieur Erik Dubois

# installing git if not installed for specific distro's

if ! location="$(type -p "git")" || [ -z "git" ]; then

	echo "Installing Git"

  	sudo apt install git -y
	# check if apt-git is installed
	if which apt-get > /dev/null; then
		sudo apt-get install -y git
	fi

	# check if pacman is installed
	if which pacman > /dev/null; then
		sudo pacman -S --noconfirm git
	fi

	# check if eopkg is installed
	if which eopkg > /dev/null; then
		sudo eopkg -y install git
	fi
	
	# check if xbps is installed
	if which xbps-install > /dev/null; then
		sudo xbps-install -Suy git
	fi
fi

#setting up git
git init
git config --global user.name "addy-dclxvi"
git config --global user.email "addy4rock@gmail.com"
sudo git config --system core.editor nano
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=18000'
git config --global push.default simple

echo "Ok"
