#!/bin/bash

# rofi launch script to use color from xrdb
# cheers! addy

# get colors from xrdb
FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')

# launch script
rofi -sidebar-mode \
-modi run,drun,window \
-hide-scrollbar true \
-show drun \
-lines 12 \
-padding 18 \
-width 60 \
-location 0 \
-columns 3 \
-font "Noto Sans 8" \
-color-enabled true \
-color-window "$BACKGROUND,$BACKGROUND,$BACKGROUND" \
-color-normal "$BACKGROUND,$FOREGROUND,$BACKGROUND,$BACKGROUND,$BLUE" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND,$BACKGROUND,$CYAN" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND,$BACKGROUND,$YELLOW"   

