#! /bin/sh

## get colors from xrdb
xrdb ~/.Xresources
FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')

## bspwm configurations
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI'
bspc config focus_follows_pointer true
bspc config border_width 4
bspc config window_gap 16
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config single_monocle false

## window rules
# 1 > terminal
bspc rule -a URxvt desktop='^1' follow=on focus=on
# 2 > web
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^2' follow=on focus=on
# 3 > file
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a File-roller desktop='^3' follow=on focus=on
# 4 > office
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^4' follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a Soffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a *:libreofficedev desktop='^4' follow=on focus=on
bspc rule -a *:soffice desktop='^4' follow=on focus=on
bspc rule -a Evince desktop='^4' follow=on focus=on
bspc rule -a Gucharmap desktop='^4' follow=on focus=on
# 5 > media
bspc rule -a Audacity desktop='^5' follow=on focus=on
bspc rule -a mpv desktop='^5' follow=on focus=on
bspc rule -a Gimp desktop='^5' follow=on focus=on
bspc rule -a Gimp-2.8 desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on
# 6 > settings
bspc rule -a Lxappearance desktop='^6' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^6' state=floating follow=on
bspc rule -a Lxtask desktop='^6' state=floating follow=on
bspc rule -a GParted desktop='^6' follow=on focus=on
bspc rule -a Pavucontrol desktop='^6' state=floating follow=on
bspc rule -a Exo-helper-1 desktop='^6' state=floating follow=on
bspc rule -a Lxrandr desktop='^6' state=floating follow=on
bspc rule -a Arandr desktop='^6' state=floating follow=on
# special rules
bspc rule -a Audacious state=floating follow=on
bspc rule -a Firefox:Places state=floating
bspc rule -a Viewnior state=floating follow=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## autostart
export PATH="${PATH}:$HOME/.scripts"
export PATH="${PATH}:$HOME/.config/bspwm"
hsetroot -center ~/.wallpaper.jpg
xsetroot -cursor_name left_ptr
xbacklight -set 10
xset fp+ ~/.fonts/misc
killall -9 xcape sxhkd lemonbar xsettingsd dunst
xcape -e 'Super_L=Super_L|D' &
sxhkd &
panel &
xsettingsd &
dunst \
-lb "$BACKGROUND" \
-lf "$FOREGROUND" \
-lfr "$GREEN" \
-nb "$BACKGROUND" \
-nf "$FOREGROUND" \
-nfr "$BLUE" \
-cb "$BACKGROUND" \
-cf "$FOREGROUND" \
-cfr "$RED" &
sleep 1
notify-send "Notification" "Bspwmrc Reloaded" &
