#! /bin/sh

## bspwm configurations
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI'
bspc config focus_follows_pointer true
bspc config border_width        4
bspc config window_gap         	16
bspc config focused_border_color "#4c566a" 
bspc config normal_border_color "#343c48"

## window rule
# 1 > terminal
bspc rule -a URxvt desktop='^1' follow=on focus=on
# 2 > web
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^2' follow=on focus=on
# 3 > file
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a File-roller desktop='^3' follow=on focus=on
# 4 > office
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^4' follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a Soffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a Evince desktop='^4' follow=on focus=on
bspc rule -a Gucharmap desktop='^4' follow=on focus=on
# 5 > media
bspc rule -a Audacity desktop='^5' follow=on focus=on
bspc rule -a mpv desktop='^5' follow=on focus=on
bspc rule -a Gimp desktop='^5' follow=on focus=on
bspc rule -a Gimp-2.8 desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on
# 6 > settings
bspc rule -a Lxappearance desktop='^6' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^6' state=floating follow=on
bspc rule -a Lxtask desktop='^6' state=floating follow=on
bspc rule -a GParted desktop='^6' follow=on focus=on
bspc rule -a Pavucontrol desktop='^6' state=floating follow=on
bspc rule -a Exo-helper-1 desktop='^6' state=floating follow=on
bspc rule -a Lxrandr desktop='^6' state=floating follow=on
bspc rule -a Arandr desktop='^6' state=floating follow=on
# special rules
bspc rule -a Audacious state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## autostart
export PATH="${PATH}:$HOME/.config/bspwm"
killall sxhkd lemonbar xsettingsd
#xset fp+ ~/.fonts/misc &
sxhkd &
xsettingsd &
panel &
xsetroot -solid "#906873"
xsetroot -cursor_name left_ptr
